name: notmuch-sync with real IMAP server

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-imap-sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - run: sudo cp $GITHUB_WORKSPACE/src/notmuch-sync /usr/bin/
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          dovecot-core \
          dovecot-imapd \
          dovecot-pop3d \
          isync \
          notmuch \
          afew libnotmuch-dev python3-notmuch2 ssh
    
    - name: Setup Dovecot IMAP server
      run: |
        # Create test user
        sudo useradd -m -s /bin/bash imapuser
        echo "imapuser:testpass" | sudo chpasswd
        
        # Create mail directory
        sudo mkdir -p /home/imapuser/Maildir/{cur,new,tmp}
        sudo chown -R imapuser:imapuser /home/imapuser/Maildir
        sudo chmod -R 700 /home/imapuser/Maildir
        
        # Configure Dovecot
        sudo tee /etc/dovecot/dovecot.conf > /dev/null <<EOF
        protocols = imap
        listen = 127.0.0.1
        
        mail_location = maildir:~/Maildir
        
        userdb {
          driver = passwd
        }
        
        passdb {
          driver = pam
        }
        
        service imap-login {
          inet_listener imap {
            port = 143
          }
        }
        
        service imap {
          process_limit = 1024
        }
        
        ssl = no
        disable_plaintext_auth = no
        
        auth_mechanisms = plain login
        
        log_path = /var/log/dovecot.log
        info_log_path = /var/log/dovecot-info.log
        debug_log_path = /var/log/dovecot-debug.log
        
        mail_debug = yes
        auth_debug = yes
        auth_verbose = yes
        EOF
        sudo systemctl start dovecot
    
    - name: Seed initial emails
      run: |
        sudo -u imapuser tee /home/imapuser/Maildir/new/1436256389.M802838P30713V0000000000000801I0000000000000008D9_0.example.org > /dev/null <<EOF
        From: sender1@example.com
        To: imapuser@localhost
        Subject: Test Email 1
        Date: $(date -R)
        Message-ID: <msg1@example.com>
        
        This is the first test email body.
        EOF
        
        sudo -u imapuser tee /home/imapuser/Maildir/new/1436256389.M802838P30713V0000000000000801I0000000000000008D8_0.example.org > /dev/null <<EOF
        From: sender2@example.com
        To: imapuser@localhost
        Subject: Test Email 2
        Date: $(date -R)
        Message-ID: <msg2@example.com>
        
        This is the second test email body.
        EOF
        
        sudo -u imapuser tee /home/imapuser/Maildir/new/1436256389.M802838P30713V0000000000000801I0000000000000008D7_0.example.org > /dev/null <<EOF
        From: sender2@example.com
        To: imapuser@localhost
        Subject: Test Email 3
        Date: $(date -R)
        Message-ID: <msg3@example.com>
        
        This is the third test email body.
        EOF

        sudo chown -R imapuser:imapuser /home/imapuser/Maildir
        sudo chmod -R 700 /home/imapuser/Maildir
        sudo systemctl restart dovecot

    - name: Configure mbsync user runner
      run: |
        mkdir -p ~/.config/mbsync
        tee ~/.config/mbsync/config > /dev/null <<EOF
        IMAPAccount testaccount
        Host 127.0.0.1
        Port 143
        User imapuser
        Pass testpass
        SSLType None
        AuthMechs LOGIN
        
        IMAPStore testaccount-remote
        Account testaccount
        
        MaildirStore testaccount-local
        Path $GITHUB_WORKSPACE/mail
        Inbox $GITHUB_WORKSPACE/mail/INBOX
        SubFolders Verbatim
        
        Channel testaccount
        Far :testaccount-remote:
        Near :testaccount-local:
        Patterns *
        Create Both
        SyncState *
        EOF

        mkdir -p $GITHUB_WORKSPACE/mail/{INBOX,Trash}/{cur,new,tmp}
    
    - name: Configure mbsync user synctest
      run: |
        sudo adduser --disabled-password --gecos "synctest" synctest
        sudo -u synctest mkdir -p /home/synctest/.config/mbsync
        sudo -u synctest tee /home/synctest/.config/mbsync/config > /dev/null <<EOF
        IMAPAccount testaccount
        Host 127.0.0.1
        Port 143
        User imapuser
        Pass testpass
        SSLType None
        AuthMechs LOGIN
        
        IMAPStore testaccount-remote
        Account testaccount
        
        MaildirStore testaccount-local
        Path ~/mail
        Inbox ~/mail/INBOX
        SubFolders Verbatim
        
        Channel testaccount
        Far :testaccount-remote:
        Near :testaccount-local:
        Patterns *
        Create Both
        SyncState *
        EOF
    
    - name: Run initial mbsync
      run: |
        echo "Running initial mbsync..."
        mbsync -a --debug-sync -V -c ~/.config/mbsync/config
    
    - name: Set up notmuch etc
      run: |
        echo -e "[database]\npath=$GITHUB_WORKSPACE/mail\nhook_dir=$GITHUB_WORKSPACE/.notmuch\n\n[user]\nname=test\nprimary_email=imapuser@localhost\n\n[new]\ntags=unread;\nignore=\n\n[search]\nexclude_tags=deleted\n[maildir]\nsynchronize_flags=true" > ~/.notmuch-config
        notmuch new
        notmuch tag +one subject:1
        notmuch tag +two subject:2
        notmuch tag +three subject:3
        mkdir -p ~/.config/afew
        echo -e "[MailMover]\nfolders = INBOX\nrename=True\nINBOX = 'tag:deleted':Trash" > ~/.config/afew/config
        echo -e "[database]\npath=/home/synctest/mail\nhook_dir=/home/synctest/.notmuch\n\n[user]\nname=test\nprimary_email=imapuser@localhost\n\n[new]\ntags=unread;\nignore=\n\n[search]\nexclude_tags=deleted\n[maildir]\nsynchronize_flags=true" > /tmp/.notmuch-config
        sudo -u synctest cp /tmp/.notmuch-config /home/synctest/
        sudo -u synctest mkdir /home/synctest/mail
        sudo -u synctest notmuch new

    - name: Set up SSH
      run: |
        mkdir ~/.ssh
        chmod 700 ~/.ssh
        ssh-keygen -N "" -f ~/.ssh/test
        echo -e "Host localhost\n IdentityFile ~/.ssh/test\n StrictHostKeyChecking no" > ~/.ssh/config
        sudo -u synctest mkdir /home/synctest/.ssh
        sudo -u synctest chmod 700 /home/synctest/.ssh
        sudo cp ~/.ssh/test.pub /home/synctest/.ssh/authorized_keys
        sudo cp ~/.ssh/config /home/synctest/.ssh/config
        sudo chown synctest /home/synctest/.ssh/authorized_keys
        sudo chown synctest /home/synctest/.ssh/config
        sudo chmod 600 /home/synctest/.ssh/authorized_keys
        sudo service ssh start
    
    # test initial sync
    - run: time notmuch-sync --delete --verbose --mbsync --remote localhost --user synctest
    - run: notmuch dump | sort > /tmp/dump.local
    - run: sudo -u synctest notmuch dump | sort > /tmp/dump.remote
    - run: diff -u /tmp/dump.local /tmp/dump.remote
    - run: notmuch search --output=files '*' | sed "s|$GITHUB_WORKSPACE||" | sort > /tmp/files.local
    - run: sudo -u synctest notmuch search --output=files '*' | sed "s|/home/synctest||" | sort > /tmp/files.remote
    - run: diff -u /tmp/files.local /tmp/files.remote
    - run: find $GITHUB_WORKSPACE/mail -type f | grep -v '\.notmuch' | sed "s|$GITHUB_WORKSPACE||" | sort > /tmp/files.local
    - run: sudo -u synctest find /home/synctest/mail -type f | grep -v '\.notmuch' | sed "s|/home/synctest||" | sort > /tmp/files.remote
    - run: diff -u /tmp/files.local /tmp/files.remote
    - run: sudo -u synctest mbsync -a --debug-sync -V -c /home/synctest/.config/mbsync/config
    - run: sudo diff -u $GITHUB_WORKSPACE/mail/INBOX/.uidvalidity /home/synctest/mail/INBOX/.uidvalidity
    - run: sudo diff -u $GITHUB_WORKSPACE/mail/INBOX/.mbsyncstate /home/synctest/mail/INBOX/.mbsyncstate

    # add mail, sync again
    - run: |
        sudo -u imapuser tee /home/imapuser/Maildir/new/1436256389.M802838P30713V0000000000000801I0000000000000008D6_0.example.org > /dev/null <<EOF
        From: sender1@example.com
        To: imapuser@localhost
        Subject: Test Email new
        Date: $(date -R)
        Message-ID: <msg4@example.com>
        
        This is another email body.
        EOF
        sudo systemctl restart dovecot
    - run: mbsync -a --debug-sync -V -c ~/.config/mbsync/config && notmuch new
    - run: time notmuch-sync --delete --verbose --mbsync --remote localhost --user synctest
    - run: notmuch dump | sort > /tmp/dump.local
    - run: sudo -u synctest notmuch dump | sort > /tmp/dump.remote
    - run: diff -u /tmp/dump.local /tmp/dump.remote
    - run: notmuch search --output=files '*' | sed "s|$GITHUB_WORKSPACE||" | sort > /tmp/files.local
    - run: sudo -u synctest notmuch search --output=files '*' | sed "s|/home/synctest||" | sort > /tmp/files.remote
    - run: diff -u /tmp/files.local /tmp/files.remote
    - run: find $GITHUB_WORKSPACE/mail -type f | grep -v '\.notmuch' | sed "s|$GITHUB_WORKSPACE||" | sort > /tmp/files.local
    - run: sudo -u synctest find /home/synctest/mail -type f | grep -v '\.notmuch' | sed "s|/home/synctest||" | sort > /tmp/files.remote
    - run: diff -u /tmp/files.local /tmp/files.remote
    - run: sudo -u synctest mbsync -a --debug-sync -V -c /home/synctest/.config/mbsync/config
    - run: sudo diff -u $GITHUB_WORKSPACE/mail/INBOX/.uidvalidity /home/synctest/mail/INBOX/.uidvalidity
    - run: sudo diff -u $GITHUB_WORKSPACE/mail/INBOX/.mbsyncstate /home/synctest/mail/INBOX/.mbsyncstate

    # same again, but from other side
    - run: |
        sudo -u imapuser tee /home/imapuser/Maildir/new/1436256389.M802838P30713V0000000000000801I0000000000000008D5_0.example.org > /dev/null <<EOF
        From: sender1@example.com
        To: imapuser@localhost
        Subject: Test Email new again
        Date: $(date -R)
        Message-ID: <msg5@example.com>
        
        This is yet another email body.
        EOF
        sudo systemctl restart dovecot
    - run: sudo -u synctest mbsync -a --debug-sync -V -c /home/synctest/.config/mbsync/config && sudo -u synctest notmuch new
    - run: time notmuch-sync --delete --verbose --mbsync --remote localhost --user synctest
    - run: notmuch dump | sort > /tmp/dump.local
    - run: sudo -u synctest notmuch dump | sort > /tmp/dump.remote
    - run: diff -u /tmp/dump.local /tmp/dump.remote
    - run: notmuch search --output=files '*' | sed "s|$GITHUB_WORKSPACE||" | sort > /tmp/files.local
    - run: sudo -u synctest notmuch search --output=files '*' | sed "s|/home/synctest||" | sort > /tmp/files.remote
    - run: diff -u /tmp/files.local /tmp/files.remote
    - run: find $GITHUB_WORKSPACE/mail -type f | grep -v '\.notmuch' | sed "s|$GITHUB_WORKSPACE||" | sort > /tmp/files.local
    - run: sudo -u synctest find /home/synctest/mail -type f | grep -v '\.notmuch' | sed "s|/home/synctest||" | sort > /tmp/files.remote
    - run: diff -u /tmp/files.local /tmp/files.remote
    - run: mbsync -a --debug-sync -V -c ~/.config/mbsync/config
    - run: sudo diff -u $GITHUB_WORKSPACE/mail/INBOX/.uidvalidity /home/synctest/mail/INBOX/.uidvalidity
    - run: sudo diff -u $GITHUB_WORKSPACE/mail/INBOX/.mbsyncstate /home/synctest/mail/INBOX/.mbsyncstate

    # same again, both sides
    - run: |
        sudo -u imapuser tee /home/imapuser/Maildir/new/1436256389.M802838P30713V0000000000000801I0000000000000008D4_0.example.org > /dev/null <<EOF
        From: sender1@example.com
        To: imapuser@localhost
        Subject: Test Email new again again
        Date: $(date -R)
        Message-ID: <msg6@example.com>
        
        This is yet another another email body.
        EOF
        sudo systemctl restart dovecot
    - run: mbsync -a --debug-sync -V -c ~/.config/mbsync/config && notmuch new
    - run: sudo -u synctest mbsync -a --debug-sync -V -c /home/synctest/.config/mbsync/config && sudo -u synctest notmuch new
    - run: time notmuch-sync --delete --verbose --verbose --mbsync --remote localhost --user synctest
    - run: notmuch dump | sort > /tmp/dump.local
    - run: sudo -u synctest notmuch dump | sort > /tmp/dump.remote
    - run: diff -u /tmp/dump.local /tmp/dump.remote
    - run: notmuch search --output=files '*' | sed "s|$GITHUB_WORKSPACE||" | sort > /tmp/files.local
    - run: sudo -u synctest notmuch search --output=files '*' | sed "s|/home/synctest||" | sort > /tmp/files.remote
    - run: diff -u /tmp/files.local /tmp/files.remote
    - run: find $GITHUB_WORKSPACE/mail -type f | grep -v '\.notmuch' | sed "s|$GITHUB_WORKSPACE||" | sort > /tmp/files.local
    - run: sudo -u synctest find /home/synctest/mail -type f | grep -v '\.notmuch' | sed "s|/home/synctest||" | sort > /tmp/files.remote
    - run: diff -u /tmp/files.local /tmp/files.remote
    - run: mbsync -a --debug-sync -V -c ~/.config/mbsync/config
    - run: sudo -u synctest mbsync -a --debug-sync -V -c /home/synctest/.config/mbsync/config
    - run: sudo diff -u $GITHUB_WORKSPACE/mail/INBOX/.uidvalidity /home/synctest/mail/INBOX/.uidvalidity
    - run: sudo diff -u $GITHUB_WORKSPACE/mail/INBOX/.mbsyncstate /home/synctest/mail/INBOX/.mbsyncstate

    # mark read
    - run: notmuch tag -unread '*'
    - run: mbsync -a --debug-sync -V -c ~/.config/mbsync/config && notmuch new
    - run: time notmuch-sync --delete --verbose --mbsync --remote localhost --user synctest
    - run: notmuch dump | sort > /tmp/dump.local
    - run: sudo -u synctest notmuch dump | sort > /tmp/dump.remote
    - run: diff -u /tmp/dump.local /tmp/dump.remote
    - run: notmuch search --output=files '*' | sed "s|$GITHUB_WORKSPACE||" | sort > /tmp/files.local
    - run: sudo -u synctest notmuch search --output=files '*' | sed "s|/home/synctest||" | sort > /tmp/files.remote
    - run: diff -u /tmp/files.local /tmp/files.remote
    - run: find $GITHUB_WORKSPACE/mail -type f | grep -v '\.notmuch' | sed "s|$GITHUB_WORKSPACE||" | sort > /tmp/files.local
    - run: sudo -u synctest find /home/synctest/mail -type f | grep -v '\.notmuch' | sed "s|/home/synctest||" | sort > /tmp/files.remote
    - run: diff -u /tmp/files.local /tmp/files.remote
    - run: sudo -u synctest mbsync -a --debug-sync -V -c /home/synctest/.config/mbsync/config
    - run: sudo diff -u $GITHUB_WORKSPACE/mail/INBOX/.uidvalidity /home/synctest/mail/INBOX/.uidvalidity
    - run: sudo diff -u $GITHUB_WORKSPACE/mail/INBOX/.mbsyncstate /home/synctest/mail/INBOX/.mbsyncstate

    # delete and move
    - run: notmuch tag +deleted '*'
    - run: afew --move-mails --verbose
    - run: mbsync -a --debug-sync -V -c ~/.config/mbsync/config && notmuch new
    - run: time notmuch-sync --delete --verbose --mbsync --remote localhost --user synctest
    - run: notmuch dump | sort > /tmp/dump.local
    - run: sudo -u synctest notmuch dump | sort > /tmp/dump.remote
    - run: diff -u /tmp/dump.local /tmp/dump.remote
    - run: notmuch search --output=files '*' | sed "s|$GITHUB_WORKSPACE||" | sort > /tmp/files.local
    - run: sudo -u synctest notmuch search --output=files '*' | sed "s|/home/synctest||" | sort > /tmp/files.remote
    - run: diff -u /tmp/files.local /tmp/files.remote
    - run: find $GITHUB_WORKSPACE/mail -type f | grep -v '\.notmuch' | sed "s|$GITHUB_WORKSPACE||" | sort > /tmp/files.local
    - run: sudo -u synctest find /home/synctest/mail -type f | grep -v '\.notmuch' | sed "s|/home/synctest||" | sort > /tmp/files.remote
    - run: diff -u /tmp/files.local /tmp/files.remote
    - run: sudo -u synctest mbsync -a --debug-sync -V -c /home/synctest/.config/mbsync/config
    - run: sudo diff -u $GITHUB_WORKSPACE/mail/INBOX/.uidvalidity /home/synctest/mail/INBOX/.uidvalidity
    - run: sudo diff -u $GITHUB_WORKSPACE/mail/INBOX/.mbsyncstate /home/synctest/mail/INBOX/.mbsyncstate
    - run: sudo diff -u $GITHUB_WORKSPACE/mail/Trash/.uidvalidity /home/synctest/mail/Trash/.uidvalidity
    - run: sudo diff -u $GITHUB_WORKSPACE/mail/Trash/.mbsyncstate /home/synctest/mail/Trash/.mbsyncstate

    - run: sudo ls -a -R $GITHUB_WORKSPACE/mail /home/synctest/mail
