name: notmuch-sync with notmuch mailing list archive

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  notmuch-ml:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - run: sudo cp $GITHUB_WORKSPACE/src/notmuch-sync /usr/bin/

    - run: sudo apt-get install -y notmuch libnotmuch-dev python3-notmuch2 wget ssh

    - run: |
        echo -e "[database]\npath=$GITHUB_WORKSPACE/notmuch-list\nhook_dir=$GITHUB_WORKSPACE/.notmuch\n\n[user]\nname=test\nprimary_email=test@test.com\n\n[new]\ntags=unread;\nignore=\n\n[search]\nexclude_tags=deleted" > ~/.notmuch-config
        wget https://nmbug.notmuchmail.org/archive/notmuch-list.tar.xz
        tar xf notmuch-list.tar.xz
        notmuch new
        notmuch tag -unread date:..1M
        notmuch tag +patch subject:patch or attachment:.patch
        notmuch tag +bug subject:bug or body:bug
        notmuch tag +question body:question or subject:'?'
        notmuch tag +todo date:1M.. and tag:patch

    - run: |
        sudo adduser --disabled-password --gecos "synctest" synctest
        echo -e "[database]\npath=/home/synctest/notmuch-list\nhook_dir=/home/synctest/.notmuch\n\n[user]\nname=test\nprimary_email=test@test.com\n\n[new]\ntags=unread;\nignore=\n\n[search]\nexclude_tags=deleted" > /tmp/.notmuch-config
        sudo -u synctest cp /tmp/.notmuch-config /home/synctest/
        sudo -u synctest mkdir /home/synctest/notmuch-list
        sudo -u synctest notmuch new

    - run: |
        mkdir ~/.ssh
        chmod 700 ~/.ssh
        ssh-keygen -N "" -f ~/.ssh/test

    - run: |
        sudo -u synctest mkdir /home/synctest/.ssh
        sudo -u synctest chmod 700 /home/synctest/.ssh
        sudo cp ~/.ssh/test.pub /home/synctest/.ssh/authorized_keys
        sudo chown synctest /home/synctest/.ssh/authorized_keys
        sudo chmod 600 /home/synctest/.ssh/authorized_keys
        sudo service ssh start

    - run: |
        # initial sync
        time notmuch-sync --delete --verbose --remote localhost --user synctest --ssh-cmd "ssh -i ~/.ssh/test -CTaxq -o StrictHostKeyChecking=no"
        notmuch dump | sort > /tmp/dump.local
        sudo -u synctest notmuch dump | sort > /tmp/dump.remote
        diff -u /tmp/dump.local /tmp/dump.remote
        notmuch search --output=files '*' | sed "s|$GITHUB_WORKSPACE||" | sort > /tmp/files.local
        sudo -u synctest notmuch search --output=files '*' | sed "s|/home/synctest||" | sort > /tmp/files.remote
        diff -u /tmp/files.local /tmp/files.remote
        find $GITHUB_WORKSPACE/notmuch-list -type f | grep -v '\.notmuch' | sed "s|$GITHUB_WORKSPACE||" | sort > /tmp/files.local
        sudo -u synctest find /home/synctest/notmuch-list -type f | grep -v '\.notmuch' | sed "s|/home/synctest||" | sort > /tmp/files.remote
        diff -u /tmp/files.local /tmp/files.remote

    - run: |
        # tag message locally
        if [ X`notmuch search --output=tags id:1517843248.cvlu0mp4mk.astroid@strange.none | tr -d '\n'` != "Xquestion" ]; then exit 1; fi
        notmuch tag +foo id:1517843248.cvlu0mp4mk.astroid@strange.none
        if [ X`notmuch search --output=tags id:1517843248.cvlu0mp4mk.astroid@strange.none | tr -d '\n'` != "Xfooquestion" ]; then exit 1; fi
        sudo -u synctest notmuch search --output=tags id:1517843248.cvlu0mp4mk.astroid@strange.none | grep -vq foo
        time notmuch-sync --delete --verbose --remote localhost --user synctest --ssh-cmd "ssh -i ~/.ssh/test -CTaxq -o StrictHostKeyChecking=no"
        notmuch dump | sort > /tmp/dump.local
        sudo -u synctest notmuch dump | sort > /tmp/dump.remote
        diff -u /tmp/dump.local /tmp/dump.remote

    - run: |
        # remove message locally
        mv `notmuch search --output=files id:1517843248.cvlu0mp4mk.astroid@strange.none` /tmp/temp1.mail
        notmuch new
        if [ X`notmuch search id:1517843248.cvlu0mp4mk.astroid@strange.none | wc -l` != "X0" ]; then exit 1; fi
        if [ X`sudo -u synctest notmuch search id:1517843248.cvlu0mp4mk.astroid@strange.none | wc -l` != "X1" ]; then exit 1; fi
        time notmuch-sync --delete --verbose --remote localhost --user synctest --ssh-cmd "ssh -i ~/.ssh/test -CTaxq -o StrictHostKeyChecking=no"
        if [ X`notmuch search id:1517843248.cvlu0mp4mk.astroid@strange.none | wc -l` != "X0" ]; then exit 1; fi
        if [ X`sudo -u synctest notmuch search id:1517843248.cvlu0mp4mk.astroid@strange.none | wc -l` != "X0" ]; then exit 1; fi
        notmuch dump | sort > /tmp/dump.local
        sudo -u synctest notmuch dump | sort > /tmp/dump.remote
        diff -u /tmp/dump.local /tmp/dump.remote
        notmuch search --output=files '*' | sed "s|$GITHUB_WORKSPACE||" | sort > /tmp/files.local
        sudo -u synctest notmuch search --output=files '*' | sed "s|/home/synctest||" | sort > /tmp/files.remote
        diff -u /tmp/files.local /tmp/files.remote
        find $GITHUB_WORKSPACE/notmuch-list -type f | grep -v '\.notmuch' | sed "s|$GITHUB_WORKSPACE||" | sort > /tmp/files.local
        sudo -u synctest find /home/synctest/notmuch-list -type f | grep -v '\.notmuch' | sed "s|/home/synctest||" | sort > /tmp/files.remote
        diff -u /tmp/files.local /tmp/files.remote

    - run: |
        # remove message on remote
        sudo -u synctest notmuch search --output=files id:1517815399.2w186vjjm2.astroid@strange.none > /tmp/todel
        sudo -u synctest mv `cat /tmp/todel` /tmp/temp2.mail
        sudo -u synctest notmuch new
        if [ X`sudo -u synctest notmuch search id:1517815399.2w186vjjm2.astroid@strange.none | wc -l` != "X0" ]; then exit 1; fi
        if [ X`notmuch search id:1517815399.2w186vjjm2.astroid@strange.none | wc -l` != "X1" ]; then exit 1; fi
        time notmuch-sync --delete --verbose --verbose --remote localhost --user synctest --ssh-cmd "ssh -i ~/.ssh/test -CTaxq -o StrictHostKeyChecking=no"
        if [ X`sudo -u synctest notmuch search id:1517815399.2w186vjjm2.astroid@strange.none | wc -l` != "X0" ]; then exit 1; fi
        if [ X`notmuch search id:1517815399.2w186vjjm2.astroid@strange.none | wc -l` != "X0" ]; then exit 1; fi
        notmuch dump | sort > /tmp/dump.local
        sudo -u synctest notmuch dump | sort > /tmp/dump.remote
        diff -u /tmp/dump.local /tmp/dump.remote
        notmuch search --output=files '*' | sed "s|$GITHUB_WORKSPACE||" | sort > /tmp/files.local
        sudo -u synctest notmuch search --output=files '*' | sed "s|/home/synctest||" | sort > /tmp/files.remote
        diff -u /tmp/files.local /tmp/files.remote
        find $GITHUB_WORKSPACE/notmuch-list -type f | grep -v '\.notmuch' | sed "s|$GITHUB_WORKSPACE||" | sort > /tmp/files.local
        sudo -u synctest find /home/synctest/notmuch-list -type f | grep -v '\.notmuch' | sed "s|/home/synctest||" | sort > /tmp/files.remote
        diff -u /tmp/files.local /tmp/files.remote

    - run: |
        # copy both local and remote messages back
        cp /tmp/temp2.mail $GITHUB_WORKSPACE/notmuch-list/
        notmuch new
        sudo -u synctest cp /tmp/temp1.mail /home/synctest/notmuch-list/
        sudo -u synctest notmuch new
        if [ X`notmuch search id:1517815399.2w186vjjm2.astroid@strange.none | wc -l` != "X1" ]; then exit 1; fi
        if [ X`sudo -u synctest notmuch search id:1517815399.2w186vjjm2.astroid@strange.none | wc -l` != "X0" ]; then exit 1; fi
        if [ X`notmuch search id:1517843248.cvlu0mp4mk.astroid@strange.none | wc -l` != "X0" ]; then exit 1; fi
        if [ X`sudo -u synctest notmuch search id:1517843248.cvlu0mp4mk.astroid@strange.none | wc -l` != "X1" ]; then exit 1; fi
        time notmuch-sync --delete --verbose --verbose --remote localhost --user synctest --ssh-cmd "ssh -i ~/.ssh/test -CTaxq -o StrictHostKeyChecking=no"
        if [ X`notmuch search id:1517815399.2w186vjjm2.astroid@strange.none | wc -l` != "X1" ]; then exit 1; fi
        if [ X`sudo -u synctest notmuch search id:1517815399.2w186vjjm2.astroid@strange.none | wc -l` != "X1" ]; then exit 1; fi
        if [ X`notmuch search id:1517843248.cvlu0mp4mk.astroid@strange.none | wc -l` != "X1" ]; then exit 1; fi
        if [ X`sudo -u synctest notmuch search id:1517843248.cvlu0mp4mk.astroid@strange.none | wc -l` != "X1" ]; then exit 1; fi
        notmuch dump | sort > /tmp/dump.local
        sudo -u synctest notmuch dump | sort > /tmp/dump.remote
        diff -u /tmp/dump.local /tmp/dump.remote
        notmuch search --output=files '*' | sed "s|$GITHUB_WORKSPACE||" | sort > /tmp/files.local
        sudo -u synctest notmuch search --output=files '*' | sed "s|/home/synctest||" | sort > /tmp/files.remote
        diff -u /tmp/files.local /tmp/files.remote
        find $GITHUB_WORKSPACE/notmuch-list -type f | grep -v '\.notmuch' | sed "s|$GITHUB_WORKSPACE||" | sort > /tmp/files.local
        sudo -u synctest find /home/synctest/notmuch-list -type f | grep -v '\.notmuch' | sed "s|/home/synctest||" | sort > /tmp/files.remote
        diff -u /tmp/files.local /tmp/files.remote
