name: notmuch-sync with notmuch mailing list archive

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  notmuch-ml:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - run: sudo cp $GITHUB_WORKSPACE/src/notmuch-sync /usr/bin/

    - run: sudo apt-get install -y notmuch libnotmuch-dev python3-notmuch2 wget ssh

    - run: |
        echo -e "[database]\npath=$GITHUB_WORKSPACE/notmuch-list\nhook_dir=$GITHUB_WORKSPACE/.notmuch\n\n[user]\nname=test\nprimary_email=test@test.com\n\n[new]\ntags=unread;\nignore=\n\n[search]\nexclude_tags=deleted" > ~/.notmuch-config
        wget https://nmbug.notmuchmail.org/archive/notmuch-list.tar.xz
        tar xf notmuch-list.tar.xz
        notmuch new
        notmuch tag -unread date:..1M
        notmuch tag +patch subject:patch or attachment:.patch
        notmuch tag +bug subject:bug or body:bug
        notmuch tag +question body:question or subject:'?'
        notmuch tag +todo date:1M.. and tag:patch

    - run: |
        sudo adduser --disabled-password --gecos "synctest" synctest
        echo -e "[database]\npath=/home/synctest/notmuch-list\nhook_dir=/home/synctest/.notmuch\n\n[user]\nname=test\nprimary_email=test@test.com\n\n[new]\ntags=unread;\nignore=\n\n[search]\nexclude_tags=deleted" > /tmp/.notmuch-config
        sudo -u synctest cp /tmp/.notmuch-config /home/synctest/
        sudo -u synctest mkdir /home/synctest/notmuch-list
        sudo -u synctest notmuch new

    - run: |
        mkdir ~/.ssh
        chmod 700 ~/.ssh
        ssh-keygen -N "" -f ~/.ssh/test
        echo -e "Host localhost\n IdentityFile ~/.ssh/test\n StrictHostKeyChecking no" > ~/.ssh/config
        sudo -u synctest mkdir /home/synctest/.ssh
        sudo -u synctest chmod 700 /home/synctest/.ssh
        sudo cp ~/.ssh/test.pub /home/synctest/.ssh/authorized_keys
        sudo cp ~/.ssh/config /home/synctest/.ssh/config
        sudo chown synctest /home/synctest/.ssh/authorized_keys
        sudo chown synctest /home/synctest/.ssh/config
        sudo chmod 600 /home/synctest/.ssh/authorized_keys
        sudo service ssh start

    # initial sync
    - run: time notmuch-sync --delete --verbose --remote localhost --user synctest
    - run: notmuch dump | sort > /tmp/dump.local
    - run: sudo -u synctest notmuch dump | sort > /tmp/dump.remote
    - run: diff -u /tmp/dump.local /tmp/dump.remote
    - run: notmuch search --output=files '*' | sed "s|$GITHUB_WORKSPACE||" | sort > /tmp/files.local
    - run: sudo -u synctest notmuch search --output=files '*' | sed "s|/home/synctest||" | sort > /tmp/files.remote
    - run: diff -u /tmp/files.local /tmp/files.remote
    - run: find $GITHUB_WORKSPACE/notmuch-list -type f | grep -v '\.notmuch' | sed "s|$GITHUB_WORKSPACE||" | sort > /tmp/files.local
    - run: sudo -u synctest find /home/synctest/notmuch-list -type f | grep -v '\.notmuch' | sed "s|/home/synctest||" | sort > /tmp/files.remote
    - run: diff -u /tmp/files.local /tmp/files.remote

    # tag message locally
    - run: if [ X`notmuch search --output=tags id:1517843248.cvlu0mp4mk.astroid@strange.none | tr -d '\n'` != "Xquestion" ]; then exit 1; fi
    - run: notmuch tag +foo id:1517843248.cvlu0mp4mk.astroid@strange.none
    - run: if [ X`notmuch search --output=tags id:1517843248.cvlu0mp4mk.astroid@strange.none | tr -d '\n'` != "Xfooquestion" ]; then exit 1; fi
    - run: sudo -u synctest notmuch search --output=tags id:1517843248.cvlu0mp4mk.astroid@strange.none | grep -vq foo
    - run: time notmuch-sync --delete --verbose --remote localhost --user synctest
    - run: notmuch dump | sort > /tmp/dump.local
    - run: sudo -u synctest notmuch dump | sort > /tmp/dump.remote
    - run: diff -u /tmp/dump.local /tmp/dump.remote

    # remove message locally
    - run: mv `notmuch search --output=files id:1517843248.cvlu0mp4mk.astroid@strange.none` /tmp/temp1.mail
    - run: notmuch new
    - run: if [ X`notmuch search id:1517843248.cvlu0mp4mk.astroid@strange.none | wc -l` != "X0" ]; then exit 1; fi
    - run: if [ X`sudo -u synctest notmuch search id:1517843248.cvlu0mp4mk.astroid@strange.none | wc -l` != "X1" ]; then exit 1; fi
    - run: time notmuch-sync --delete --verbose --remote localhost --user synctest
    - run: if [ X`notmuch search id:1517843248.cvlu0mp4mk.astroid@strange.none | wc -l` != "X0" ]; then exit 1; fi
    - run: if [ X`sudo -u synctest notmuch search id:1517843248.cvlu0mp4mk.astroid@strange.none | wc -l` != "X0" ]; then exit 1; fi
    - run: notmuch dump | sort > /tmp/dump.local
    - run: sudo -u synctest notmuch dump | sort > /tmp/dump.remote
    - run: diff -u /tmp/dump.local /tmp/dump.remote
    - run: notmuch search --output=files '*' | sed "s|$GITHUB_WORKSPACE||" | sort > /tmp/files.local
    - run: sudo -u synctest notmuch search --output=files '*' | sed "s|/home/synctest||" | sort > /tmp/files.remote
    - run: diff -u /tmp/files.local /tmp/files.remote
    - run: find $GITHUB_WORKSPACE/notmuch-list -type f | grep -v '\.notmuch' | sed "s|$GITHUB_WORKSPACE||" | sort > /tmp/files.local
    - run: sudo -u synctest find /home/synctest/notmuch-list -type f | grep -v '\.notmuch' | sed "s|/home/synctest||" | sort > /tmp/files.remote
    - run: diff -u /tmp/files.local /tmp/files.remote

    # remove message on remote
    - run: sudo -u synctest notmuch search --output=files id:1517815399.2w186vjjm2.astroid@strange.none > /tmp/todel
    - run: sudo -u synctest mv `cat /tmp/todel` /tmp/temp2.mail
    - run: sudo -u synctest notmuch new
    - run: if [ X`sudo -u synctest notmuch search id:1517815399.2w186vjjm2.astroid@strange.none | wc -l` != "X0" ]; then exit 1; fi
    - run: if [ X`notmuch search id:1517815399.2w186vjjm2.astroid@strange.none | wc -l` != "X1" ]; then exit 1; fi
    - run: time notmuch-sync --delete --verbose --verbose --remote localhost --user synctest
    - run: if [ X`sudo -u synctest notmuch search id:1517815399.2w186vjjm2.astroid@strange.none | wc -l` != "X0" ]; then exit 1; fi
    - run: if [ X`notmuch search id:1517815399.2w186vjjm2.astroid@strange.none | wc -l` != "X0" ]; then exit 1; fi
    - run: notmuch dump | sort > /tmp/dump.local
    - run: sudo -u synctest notmuch dump | sort > /tmp/dump.remote
    - run: diff -u /tmp/dump.local /tmp/dump.remote
    - run: notmuch search --output=files '*' | sed "s|$GITHUB_WORKSPACE||" | sort > /tmp/files.local
    - run: sudo -u synctest notmuch search --output=files '*' | sed "s|/home/synctest||" | sort > /tmp/files.remote
    - run: diff -u /tmp/files.local /tmp/files.remote
    - run: find $GITHUB_WORKSPACE/notmuch-list -type f | grep -v '\.notmuch' | sed "s|$GITHUB_WORKSPACE||" | sort > /tmp/files.local
    - run: sudo -u synctest find /home/synctest/notmuch-list -type f | grep -v '\.notmuch' | sed "s|/home/synctest||" | sort > /tmp/files.remote
    - run: diff -u /tmp/files.local /tmp/files.remote

    # copy both local and remote messages back
    - run: cp /tmp/temp2.mail $GITHUB_WORKSPACE/notmuch-list/
    - run: notmuch new
    - run: sudo -u synctest cp /tmp/temp1.mail /home/synctest/notmuch-list/
    - run: sudo -u synctest notmuch new
    - run: if [ X`notmuch search id:1517815399.2w186vjjm2.astroid@strange.none | wc -l` != "X1" ]; then exit 1; fi
    - run: if [ X`sudo -u synctest notmuch search id:1517815399.2w186vjjm2.astroid@strange.none | wc -l` != "X0" ]; then exit 1; fi
    - run: if [ X`notmuch search id:1517843248.cvlu0mp4mk.astroid@strange.none | wc -l` != "X0" ]; then exit 1; fi
    - run: if [ X`sudo -u synctest notmuch search id:1517843248.cvlu0mp4mk.astroid@strange.none | wc -l` != "X1" ]; then exit 1; fi
    - run: time notmuch-sync --delete --verbose --verbose --remote localhost --user synctest
    - run: if [ X`notmuch search id:1517815399.2w186vjjm2.astroid@strange.none | wc -l` != "X1" ]; then exit 1; fi
    - run: if [ X`sudo -u synctest notmuch search id:1517815399.2w186vjjm2.astroid@strange.none | wc -l` != "X1" ]; then exit 1; fi
    - run: if [ X`notmuch search id:1517843248.cvlu0mp4mk.astroid@strange.none | wc -l` != "X1" ]; then exit 1; fi
    - run: if [ X`sudo -u synctest notmuch search id:1517843248.cvlu0mp4mk.astroid@strange.none | wc -l` != "X1" ]; then exit 1; fi
    - run: notmuch dump | sort > /tmp/dump.local
    - run: sudo -u synctest notmuch dump | sort > /tmp/dump.remote
    - run: diff -u /tmp/dump.local /tmp/dump.remote
    - run: notmuch search --output=files '*' | sed "s|$GITHUB_WORKSPACE||" | sort > /tmp/files.local
    - run: sudo -u synctest notmuch search --output=files '*' | sed "s|/home/synctest||" | sort > /tmp/files.remote
    - run: diff -u /tmp/files.local /tmp/files.remote
    - run: find $GITHUB_WORKSPACE/notmuch-list -type f | grep -v '\.notmuch' | sed "s|$GITHUB_WORKSPACE||" | sort > /tmp/files.local
    - run: sudo -u synctest find /home/synctest/notmuch-list -type f | grep -v '\.notmuch' | sed "s|/home/synctest||" | sort > /tmp/files.remote
    - run: diff -u /tmp/files.local /tmp/files.remote

    # same again, but kill process to check that it works when interrupted
    - run: mv `notmuch search --output=files id:1517843248.cvlu0mp4mk.astroid@strange.none` /tmp/temp1.mail
    - run: notmuch new
    - run: sudo -u synctest notmuch search --output=files id:1517815399.2w186vjjm2.astroid@strange.none > /tmp/todel
    - run: sudo -u synctest mv `cat /tmp/todel` /tmp/temp2.mail
    - run: sudo -u synctest notmuch new
    - run: time notmuch-sync --delete --verbose --remote localhost --user synctest
    - run: cp /tmp/temp2.mail $GITHUB_WORKSPACE/notmuch-list/
    - run: notmuch new
    - run: sudo -u synctest cp /tmp/temp1.mail /home/synctest/notmuch-list/
    - run: sudo -u synctest notmuch new
    - run: if [ X`notmuch search id:1517815399.2w186vjjm2.astroid@strange.none | wc -l` != "X1" ]; then exit 1; fi
    - run: if [ X`sudo -u synctest notmuch search id:1517815399.2w186vjjm2.astroid@strange.none | wc -l` != "X0" ]; then exit 1; fi
    - run: if [ X`notmuch search id:1517843248.cvlu0mp4mk.astroid@strange.none | wc -l` != "X0" ]; then exit 1; fi
    - run: if [ X`sudo -u synctest notmuch search id:1517843248.cvlu0mp4mk.astroid@strange.none | wc -l` != "X1" ]; then exit 1; fi
    - run: cp $GITHUB_WORKSPACE/notmuch-list/.notmuch/notmuch-sync-* /tmp/
    - run: sudo -u synctest cp /home/synctest/notmuch-list/.notmuch/notmuch-sync-* /tmp/
    - run: grep -m 1 "Tags synced." <(stdbuf -eL notmuch-sync --delete --verbose --verbose --remote localhost --user synctest 2>&1)
    - run: time notmuch-sync --delete --verbose --remote localhost --user synctest
    - run: if [ X`notmuch search id:1517815399.2w186vjjm2.astroid@strange.none | wc -l` != "X1" ]; then exit 1; fi
    - run: if [ X`sudo -u synctest notmuch search id:1517815399.2w186vjjm2.astroid@strange.none | wc -l` != "X1" ]; then exit 1; fi
    - run: if [ X`notmuch search id:1517843248.cvlu0mp4mk.astroid@strange.none | wc -l` != "X1" ]; then exit 1; fi
    - run: if [ X`sudo -u synctest notmuch search id:1517843248.cvlu0mp4mk.astroid@strange.none | wc -l` != "X1" ]; then exit 1; fi
    - run: notmuch dump | sort > /tmp/dump.local
    - run: sudo -u synctest notmuch dump | sort > /tmp/dump.remote
    - run: diff -u /tmp/dump.local /tmp/dump.remote
    - run: notmuch search --output=files '*' | sed "s|$GITHUB_WORKSPACE||" | sort > /tmp/files.local
    - run: wc -l /tmp/files.local
    - run: sudo -u synctest notmuch search --output=files '*' | sed "s|/home/synctest||" | sort > /tmp/files.remote
    - run: wc -l /tmp/files.remote
    - run: diff -u /tmp/files.local /tmp/files.remote
    - run: find $GITHUB_WORKSPACE/notmuch-list -type f | grep -v '\.notmuch' | sed "s|$GITHUB_WORKSPACE||" | sort > /tmp/files.local
    - run: sudo -u synctest find /home/synctest/notmuch-list -type f | grep -v '\.notmuch' | sed "s|/home/synctest||" | sort > /tmp/files.remote
    - run: diff -u /tmp/files.local /tmp/files.remote
